name: Flask App Tests

on: # Specifies the GitHub events that trigger the workflow
    pull_request: # Trigger the workflow on pull request events
        branches:
            - main # Only trigger for pull requests to the main branch

jobs: # Jobs to be executed by the workflow
    test:  # Defines a job named "test"
        runs-on: ubuntu-latest # Specifies the type of runner that the job will run on, in this case, the latest Ubuntu
        defaults: # Default settings for all the run commands within this job
            run:
                working-directory: ./app/ # Sets the default working directory for steps in the job

        strategy: # Strategy for the job execution
            matrix: # Define a matrix of different configurations to be tested
                python-version: [3.8] # List of Python versions to use, here it's only 3.12
        
        env: # Environment variables to be available to all steps in the job
            MODE: "dev" # Setting MODE variable to "dev"
        
        steps: # Steps represent a sequence of tasks that will be executed as part of the job
            - uses: actions/checkout@v3 # Uses a pre-built action to check out the repository so the workflow can access it


            - name: Set up Python # Descriptive name for the step
              uses: actions/setup-python@v4 # Uses a pre-built action to set up a Python environment
              with:
                python-version: ${{ matrix.python-version }} # Specify the Python version from the strategy matrix
            
            - name: Install dependencies
              run: |  # Commands to run as part of this step
                python -m pip install --upgrade pip 
                pip install -r /Users/sarahlin/GitHub/KnowPlay/action-faction/requirement.txt
            
            - name: Test App Code  # Descriptive name for the step
              run: python ./main_test.py # Runs the test script located in the working directory

